export default function Head() {
  return (
    <>
      <title>To Do App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta httpEquiv="Content-Language" content="en" />
      <link rel="icon" href="/todo-ico.png" />
    </>
  )
}
