import '@/styles/globals.css'
import Navbar from '@/components/navbar/navbar'
import Provider from '@/components/context'
import SideBar from '@/components/sidebar'
import { Roboto_Mono } from 'next/font/google';

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export const metadata = {
  title: 'To Do App',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto_mono.variable}`} >
      <head />
      <body className='flex flex-col bg-main md:flex-row w-screen h-screen '>
        <Provider>
          <div className='hidden md:flex'>
            <SideBar />
          </div>
          <Navbar />
          <div className='mx-8 mt-4 md:w-full' >
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}



// export default function Head() {
//   return (
//     <>
//       <title>To Do App</title>
//       <meta content="width=device-width, initial-scale=1" name="viewport" />
//       <meta name="description" content="Generated by create next app" />
//       <meta httpEquiv="Content-Language" content="en" />
//       <link rel="icon" href="/todo-ico.png" />
//     </>
//   )
// }
